conjob:
  docker:
    username: ${DOCKER_USERNAME:-}
    password: ${DOCKER_PASSWORD:-}
    containerRuntime: ${CONTAINER_RUNTIME:-sysbox_runc}
  admin:
    username: ${ADMIN_USERNAME:-}
    password: ${ADMIN_PASSWORD:-}
  auth:
    username: ${USERNAME:-}
    password: ${PASSWORD:-}
  job:
    limit:
      maxGlobalRequestsPerSecond: ${JOB_LIMIT_REQ:-5}
      maxConcurrentRuns: ${JOB_LIMIT_CONCURRENT:-3}
      maxTimeoutSeconds: ${JOB_LIMIT_TIMEOUT:-2700}
      maxKillTimeoutSeconds: ${JOB_LIMIT_KILL_TIMEOUT:-300}

server:
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: /opt/keystore.p12
      keyStorePassword: ${KEYSTORE_PASSWORD:-}
      disableSniHostCheck: ${DISABLE_SNI_HOST_CHECK:-false}

logging:
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] [%X{traceId}] %c: %m%n%rEx"
