---
container_name: conjob
image_name: "scottg489/conjob:{{ lookup('env', '_APP_DOCKER_IMAGE_TAG') }}"
adminUsername: "{{ lookup('env', '_ADMIN_USERNAME') }}"
adminPassword: "{{ lookup('env', '_ADMIN_PASSWORD') }}"
dockerUsername: "{{ lookup('env', '_DOCKER_USERNAME') }}"
dockerPassword: "{{ lookup('env', '_DOCKER_PASSWORD') }}"
keystorePassword: "{{ lookup('env', '_KEYSTORE_PASSWORD') }}"
containerRuntime: "{{ lookup('env', '_CONTAINER_RUNTIME') }}"
